template_path: ecmonsen-emorypipeline.yaml
stack_name: ecmonsen-emorypipeline
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "SysBio"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "amp-ad"
  # The resource owner
  OwnerEmail: "eva.monsen@sagebase.org"
